Imports

In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 320
df_scrape = pd.read_csv("./22_10_22_hls_people_hist_hub_V2.csv", sep=";")
df_scrape.drop("Unnamed: 10",axis=1, inplace=True)

# replace empty strings and zero width spaces with NaN
df_scrape.replace(r'^\s*$', np.nan, regex=True, inplace=True)
df_scrape.replace(r'^\u200b*$', np.nan, regex=True, inplace=True)

df_scrape.head(10)

,HLS_ID,HLS_URL,first_name,last_name,birth_date,death_date,text,published,author,translator,hhb_ids,hhb_forename,hhb_surname,hhb_sex,hhb_birth_date,hhb_death_date,hhb_relation_id,hhb_relation_name,hhb_relation_type
0,25265,http://hls-dhs-dss.ch/de/articles/025265/2001-...,Johann Ludwig,A Musis,8.8.1599,10.6.1662,"8.8.1599 Pfullendorf (Baden, D), 10.6.1662 Sol...",10.05.2001,Urban Fink,NaN,11502881,Johann Ludwig,A Musis,male,1599-08-08,1662-06-10,NaN,NaN,NaN
1,27932,http://hls-dhs-dss.ch/de/articles/027932/2002-...,Carlo Emanuele,A Prato,7.4.1895,17.9.1968,"7.4.1895 Trient, 17.9.1968 Genf, ursprünglich ...",21.08.2002,Mauro Cerutti,Christoph Neuenschwander,11519981,Carlo Emanuele,A Prato,male,1895-04-07,1968-09-17,NaN,NaN,NaN
2,4928,http://hls-dhs-dss.ch/de/articles/004928/2002-...,Albert von der,Aa,19.1.1894,10.7.1978,"19.1.1894 Vevey, 10.7.1978 Lausanne, reformier...",11.06.2002,Gilbert Marion,Peter Opitz,11383091,Albert,von der Aa,male,1894-01-19,1978-07-10,NaN,NaN,NaN
3,11462,http://hls-dhs-dss.ch/de/articles/011462/2001-...,Johannes,Aal,um 1500,28.5.1551,"um 1500 Bremgarten (AG), 28.5.1551 Solothurn, ...",24.01.2001,Rolf Max Kully,NaN,11420099,Johannes,Aal,male,1500-01-01,1551-05-28,NaN,NaN,NaN
4,8115,http://hls-dhs-dss.ch/de/articles/008115/2001-...,Alvar,Aalto,3.2.1898,11.5.1976,"3.2.1898 Kuortane (Finnland), 11.5.1976 Helsin...",15.05.2001,Simona Martinoli,Sabine Kraut,11403170,Alvar,Aalto,male,1898-02-03,1976-05-11,NaN,NaN,NaN
5,18417,http://hls-dhs-dss.ch/de/articles/018417/2001-...,Johann III. von,Aarberg,um 1410,1497,"um 1410, 1497. Sohn des Wilhelm, Herrn von Val...",15.05.2001,Germain Hausmann,Gertraud Gamper,11466260,Johann,von Aarberg,male,1410-01-01,1497-01-01,NaN,NaN,NaN
6,25265,http://hls-dhs-dss.ch/de/articles/025265/2001-...,Johann Ludwig,A Musis,8.8.1599,10.6.1662,"8.8.1599 Pfullendorf (Baden, D), 10.6.1662 Sol...",10.05.2001,Urban Fink,NaN,11502881,Johann Ludwig,A Musis,male,1599-08-08,1662-06-10,NaN,NaN,NaN
7,12040,http://hls-dhs-dss.ch/de/articles/012040/2000-...,Nesa von,Aarberg,1398,vor 1438,"Erstmals erwähnt 1398, vor 1438 Basel. Aus der...",18.10.2000,Veronika Feller-Vest,NaN,11423564,Nesa,von Aarberg,female,1398-01-01,1438-01-01,NaN,NaN,NaN
8,12072,http://hls-dhs-dss.ch/de/articles/012072/2017-...,Lüthold von,Aarburg,1190,7.6.1213,"1190 erstmals bezeugt, 7.6.1213. Aus dem Gesch...",08.05.2017,Romain Jurot,Ansgar Wildermann,11423816,Lüthold,von Aarburg,male,1190-01-01,1213-06-07,NaN,NaN,NaN
9,32200,http://hls-dhs-dss.ch/de/articles/032200/2001-...,Rudolf I. von,Aarburg,1296,16.7.1339,"1296 als Student in Bologna erstmals erwähnt, ...",24.01.2001,Franziska Hälg-Steffen,NaN,11551625,Rudolf,von Aarburg,male,1296-01-01,1339-07-16,NaN,NaN,NaN

## Clean Malformed HTML
https://hls-dhs-dss.ch/de/articles/019242/2007-08-09/

In [2]:
# get all records with missing first_name and last_name
df_scrape[df_scrape.first_name.isnull() & df_scrape.last_name.isnull()]

,HLS_ID,HLS_URL,first_name,last_name,birth_date,death_date,text,published,author,translator,hhb_ids,hhb_forename,hhb_surname,hhb_sex,hhb_birth_date,hhb_death_date,hhb_relation_id,hhb_relation_name,hhb_relation_type
11421,19242,http://hls-dhs-dss.ch/de/articles/019242/2007-...,NaN,NaN,NaN,1607,"1607 Therwil, katholisch, von Konstanz. Ca. 15...",NaN,André Salvisberg,NaN,11472911,Abraham,Keller,male,1557-01-01,1607-01-01,NaN,NaN,NaN

In [3]:
df_scrape.loc[11421, "first_name"] = "Abraham"
df_scrape.loc[11421, "last_name"] = "Keller"
df_scrape.loc[11421, "published"] = "09.08.2007"

## Checking for Null Values

In [4]:
df_scrape.notna().sum()

HLS_ID               25271
HLS_URL              25271
first_name           24803
last_name            25271
birth_date           24601
death_date           24641
text                 25271
published            25271
author               25271
translator            6588
hhb_ids              25205
hhb_forename         25198
hhb_surname          24742
hhb_sex              25198
hhb_birth_date       25132
hhb_death_date       24449
hhb_relation_id        102
hhb_relation_name      102
hhb_relation_type      102
dtype: int64

- first name, is clear because lots of records before 1000 didn't specify a first name
- translator, only specified if the text was translated to german (hence, fine)
- birth_date & death_date needs some investigation

In [5]:
len(df_scrape[df_scrape.birth_date.isnull() & df_scrape.hhb_birth_date.isnull()])

72

In [6]:
len(df_scrape[df_scrape.death_date.isnull() & df_scrape.hhb_death_date.isnull()])

466

In [7]:
len(df_scrape[df_scrape.birth_date.isnull() & df_scrape.hhb_birth_date.isnull() & df_scrape.death_date.isnull() & df_scrape.hhb_death_date.isnull()])

12

There are 72 birth dates and 466 death dates which we can not source from either hls or hist hub (hhb).
And there are 12 records where we can't source any date information from either source.

In [8]:
df_scrape[df_scrape.birth_date.isnull() & df_scrape.hhb_birth_date.isnull() & df_scrape.death_date.isnull() & df_scrape.hhb_death_date.isnull()]

,HLS_ID,HLS_URL,first_name,last_name,birth_date,death_date,text,published,author,translator,hhb_ids,hhb_forename,hhb_surname,hhb_sex,hhb_birth_date,hhb_death_date,hhb_relation_id,hhb_relation_name,hhb_relation_type
1848,60641,http://hls-dhs-dss.ch/de/articles/060641/2022-...,Leny,Bider,NaN,NaN,"​8.11.1894 Langenbruck,​7.7.1919 Zürich, refor...",17.08.2022,Tamara Suter,NaN,18001995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2031,59102,http://hls-dhs-dss.ch/de/articles/059102/2020-...,Henriette,Bitzius-Zeender,NaN,NaN,"​8.8.1805 Bern, ​14.6.1872 Bern, reformiert, v...",08.04.2020,Marianne Derron,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6450,10200,http://hls-dhs-dss.ch/de/articles/010200/2008-...,NaN,Felix und Regula,NaN,NaN,Das früheste Zeugnis der beiden Zürcher Stadth...,15.12.2008,Hans Stadler,NaN,11412818,Felix und Regula,NaN,male,NaN,NaN,NaN,NaN,NaN
7774,58885,http://hls-dhs-dss.ch/de/articles/058885/2020-...,Jrenäus,Gersdorf,NaN,NaN,"​1809 Monstab bei Altenburg (Thüringen), ​1860...",08.04.2020,Jesko Reiling,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10433,61175,http://hls-dhs-dss.ch/de/articles/061175/2022-...,Rosa,Häcki-Feierabend,NaN,NaN,"​5.1.1922 Engelberg, ​14.10.1996 Engelberg, ka...",26.07.2022,Heidi Wernli Gasser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12808,60087,http://hls-dhs-dss.ch/de/articles/060087/2021-...,Elsy,Leuzinger,NaN,NaN,"​7.2.1910 Kilchberg (ZH), ​27.4.2010 Zürich, r...",24.08.2021,Susanne Peter-Kubli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14474,58877,http://hls-dhs-dss.ch/de/articles/058877/2020-...,Jean-Louis,Micheli,NaN,NaN,"​16.12.1812 Genf, ​30.3.1875 Genf, reformiert,...",08.04.2020,Marianne Derron,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15367,58886,http://hls-dhs-dss.ch/de/articles/058886/2020-...,Theodor,Müller,NaN,NaN,"​12.11.1790 Strelitz-Alt, ​23.7.1857 Hofwil, p...",08.04.2020,Michael Ruloff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15440,58879,http://hls-dhs-dss.ch/de/articles/058879/2020-...,François,Naef,NaN,NaN,"​31.3.1825 Genf, ​4.11.1897 Genf, reformiert, ...",08.04.2020,Marianne Derron,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16731,58875,http://hls-dhs-dss.ch/de/articles/058875/2020-...,Adèle de,Pierre,NaN,NaN,"​1.4.1800 Neuenburg, ​5.8.1890 Neuenburg, refo...",08.04.2020,Marianne Derron,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22334,58878,http://hls-dhs-dss.ch/de/articles/058878/2020-...,Marie,Tourte-Cherbuliez,NaN,NaN,"​12.4.1793 Genf, ​19.8.1863 Plainpalais, refor...",08.04.2020,Marianne Derron,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22836,10332,http://hls-dhs-dss.ch/de/articles/010332/2014-...,NaN,Vadomar und Gundomad,NaN,NaN,Vadomar (​nach 371) und Gundomad (357) waren a...,04.03.2014,Gabrielle Duchoud,Susanne Ritter-Lutz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_scrape[df_scrape.death_date.isnull()].iloc[0].HLS_URL

'http://hls-dhs-dss.ch/de/articles/012450/2001-06-05/'

## Trying to get value out of hls date fields.

In [10]:
# str extract with date format
df_scrape.birth_date.str.extract(r"((\d{1,2}\.\d{1,2}\.\d{3,4})|(\d{4}))")
# python str.extract regex or str.extractall regex

                0           1     2
0        8.8.1599    8.8.1599   NaN
1        7.4.1895    7.4.1895   NaN
2       19.1.1894   19.1.1894   NaN
3            1500         NaN  1500
4        3.2.1898    3.2.1898   NaN
...           ...         ...   ...
25266   24.1.1887   24.1.1887   NaN
25267  11.11.1921  11.11.1921   NaN
25268    7.3.1304    7.3.1304   NaN
25269        1445         NaN  1445
25270   15.6.1558   15.6.1558   NaN

[25271 rows x 3 columns]

In [11]:
# Total Rows: (25271)
df_scrape.birth_date.isna().sum() + df_scrape.birth_date.notna().sum()

25271

In [12]:
df_scrape.birth_date.count()

24601

In [13]:
# Number of rows in birth_date being matched by regex: (24547)
df_scrape.birth_date.str.extract(r"((\d{1,2}\.\d{1,2}\.\d{3,4})|(\d{3,4}))")[0].notna().sum()

24547

The proof below shows that we indeed match the first year if specification year/year is hit:

In [14]:
df_scrape.birth_date[62:63]

62    610/611
Name: birth_date, dtype: object

In [15]:
df_scrape.birth_date.str.extract(r"((\d{1,2}\.\d{1,2}\.\d{3,4})|(\d{3,4}))")[62:63]

      0    1    2
62  610  NaN  610

Let's continue

In [16]:
# Number of rows in birth_date NOT being matched by regex: (54)
df_scrape.birth_date.notna().sum() - df_scrape.birth_date.str.extract(r"((\d{1,2}\.\d{1,2}\.\d{3,4})|(\d{3,4}))")[0].notna().sum()

54

Let's investigate those 54 records, 48 of these records have a hhb_birth_date which covers those records.

In [17]:
df_scrape[df_scrape.birth_date.str.extract(r"((\d{1,2}\.\d{1,2}\.\d{3,4})|(\d{3,4}))")[0].isna() & df_scrape.birth_date.notna() & df_scrape.hhb_birth_date.isna()]

,HLS_ID,HLS_URL,first_name,last_name,birth_date,death_date,text,published,author,translator,hhb_ids,hhb_forename,hhb_surname,hhb_sex,hhb_birth_date,hhb_death_date,hhb_relation_id,hhb_relation_name,hhb_relation_type
7769,12640,http://hls-dhs-dss.ch/de/articles/012640/2005-...,NaN,Gerold,19.4. (Geburtsjahr unbekannt),10.4. um 978,"19.4. (Geburtsjahr unbekannt), 10.4. um 978 . ...",29.08.2005,Veronika Feller-Vest,NaN,11427839,Gerold,NaN,male,NaN,0978-01-01,NaN,NaN,NaN
11695,15548,http://hls-dhs-dss.ch/de/articles/015548/2006-...,Johann,Kluser,wohl zweite Hälfte 14. Jahrhundert,nach 1437,"wohl zweite Hälfte 14. Jahrhundert, nach 1437....",14.12.2006,Hans Stadler,NaN,11447549,Johann,Kluser,male,NaN,1437-01-01,NaN,NaN,NaN
13809,58876,http://hls-dhs-dss.ch/de/articles/058876/2020-...,Edouard,Matthey,​15.6.,NaN,"​15.6.1833 Le Locle, ​23.7.1886 Prilly, reform...",08.04.2020,Marianne Derron,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14570,12835,http://hls-dhs-dss.ch/de/articles/012835/2008-...,NaN,Moengal,Mitte bis zweite Hälfte 9. Jahrhundert,an einem 30. September zwischen 868 und 895,"Mitte bis zweite Hälfte 9. Jahrhundert, an ein...",24.11.2008,Peter Stotz,NaN,11429270,Moengal,NaN,male,NaN,NaN,NaN,NaN,NaN
16168,48410,http://hls-dhs-dss.ch/de/articles/048410/2009-...,Giovan Francesco,Paleari,2. Hälfte 15. Jh.,vor 1542,"2. Hälfte 15. Jh. Morcote, vor 1542 Morcote, k...",19.06.2009,Marino Viganò,Thomas Barfuss,11590730,Giovan Francesco,Paleari,male,NaN,1542-01-01,NaN,NaN,NaN
18142,12921,http://hls-dhs-dss.ch/de/articles/012921/2010-...,NaN,Romanus,Ende des 4. Jh.,460/465,"Ende des 4. Jh., 460/465, ​La Balme (Saint-Rom...",10.11.2010,Veronika Feller-Vest,NaN,11429954,Romanus,NaN,male,NaN,0460-01-01,NaN,NaN,NaN

## Actual Cleaning of the birth date

In [18]:
df_scrape["cleaned_birth_date"] = df_scrape.birth_date.str.extract(r"((\d{1,2}\.\d{1,2}\.\d{3,4})|(\d{3,4}))")[0]
df_scrape.loc[11695, "cleaned_birth_date"] = "1.1.1375"
df_scrape.loc[13809, "cleaned_birth_date"] = "15.6.1833"
df_scrape.loc[14570, "cleaned_birth_date"] = "1.1.850"
df_scrape.loc[16168, "cleaned_birth_date"] = "1.1.1475"
df_scrape.loc[18142, "cleaned_birth_date"] = "1.1.400"

In [19]:
df_scrape["cleaned_birth_date"]

0          8.8.1599
1          7.4.1895
2         19.1.1894
3              1500
4          3.2.1898
            ...
25266     24.1.1887
25267    11.11.1921
25268      7.3.1304
25269          1445
25270     15.6.1558
Name: cleaned_birth_date, Length: 25271, dtype: object

# modify cleaned birth date to be in the format YYYY-MM-DD (format="%Y-%m-%d")

In [20]:
# 8.8.1599 -> 1599-08-08
df_scrape["cleaned_birth_date_formatted"] = df_scrape[df_scrape["cleaned_birth_date"].str.fullmatch(r"(\d{1}\.\d{1}\.\d{4})", na=False)]["cleaned_birth_date"].str.replace(r"(\d{1})\.(\d{1})\.(\d{4})", r"\3-0\2-0\1", regex=True)
# 8.8.900 -> 0900-08-08
df_scrape["cleaned_birth_date_formatted"].fillna(df_scrape[df_scrape["cleaned_birth_date"].str.fullmatch(r"(\d{1}\.\d{1}\.\d{3})", na=False)]["cleaned_birth_date"].str.replace(r"(\d{1})\.(\d{1})\.(\d{3})", r"0\3-0\2-0\1", regex=True), inplace=True)
# 14.5.1900 -> 1900-05-14
df_scrape["cleaned_birth_date_formatted"].fillna(df_scrape[df_scrape["cleaned_birth_date"].str.fullmatch(r"(\d{2}\.\d{1}\.\d{4})", na=False)]["cleaned_birth_date"].str.replace(r"(\d{2})\.(\d{1})\.(\d{4})", r"\3-0\2-\1", regex=True), inplace=True)
# 14.5.900 -> 0900-05-14
df_scrape["cleaned_birth_date_formatted"].fillna(df_scrape[df_scrape["cleaned_birth_date"].str.fullmatch(r"(\d{2}\.\d{1}\.\d{3})", na=False)]["cleaned_birth_date"].str.replace(r"(\d{2})\.(\d{1})\.(\d{3})", r"0\3-0\2-\1", regex=True), inplace=True)
# 4.05.1900 -> 1900-05-04
df_scrape["cleaned_birth_date_formatted"].fillna(df_scrape[df_scrape["cleaned_birth_date"].str.fullmatch(r"(\d{1}\.\d{2}\.\d{4})", na=False)]["cleaned_birth_date"].str.replace(r"(\d{1})\.(\d{2})\.(\d{4})", r"\3-\2-0\1", regex=True), inplace=True)
# 4.05.500 -> 0500-05-04
df_scrape["cleaned_birth_date_formatted"].fillna(df_scrape[df_scrape["cleaned_birth_date"].str.fullmatch(r"(\d{1}\.\d{2}\.\d{3})", na=False)]["cleaned_birth_date"].str.replace(r"(\d{1})\.(\d{2})\.(\d{3})", r"0\3-\2-0\1", regex=True), inplace=True)
# 18.08.1500 -> 1500-08-18
df_scrape["cleaned_birth_date_formatted"].fillna(df_scrape[df_scrape["cleaned_birth_date"].str.fullmatch(r"(\d{2}\.\d{2}\.\d{4})", na=False)]["cleaned_birth_date"].str.replace(r"(\d{2})\.(\d{2})\.(\d{4})", r"\3-\2-\1", regex=True), inplace=True)
# 18.08.900 -> 0900-08-18
df_scrape["cleaned_birth_date_formatted"].fillna(df_scrape[df_scrape["cleaned_birth_date"].str.fullmatch(r"(\d{2}\.\d{2}\.\d{3})", na=False)]["cleaned_birth_date"].str.replace(r"(\d{2})\.(\d{2})\.(\d{3})", r"0\3-\2-\1", regex=True), inplace=True)
# 900 to 0900-01-01
df_scrape["cleaned_birth_date_formatted"].fillna(df_scrape[df_scrape["cleaned_birth_date"].str.fullmatch(r"(\d{3})", na=False)]["cleaned_birth_date"].str.replace(r"(\d{3})", r"0\1-01-01", regex=True), inplace=True)
# 1500 to 1500-01-01
df_scrape["cleaned_birth_date_formatted"].fillna(df_scrape[df_scrape["cleaned_birth_date"].str.fullmatch(r"(\d{4})", na=False)]["cleaned_birth_date"].str.replace(r"(\d{4})", r"\1-01-01", regex=True), inplace=True)

In [21]:
df_scrape["cleaned_birth_date_formatted"]

0        1599-08-08
1        1895-04-07
2        1894-01-19
3        1500-01-01
4        1898-02-03
            ...
25266    1887-01-24
25267    1921-11-11
25268    1304-03-07
25269    1445-01-01
25270    1558-06-15
Name: cleaned_birth_date_formatted, Length: 25271, dtype: object

## Adding Missing Birth Dates from HHB

In [22]:
df_scrape.fillna({"cleaned_birth_date_formatted": df_scrape.hhb_birth_date}, inplace=True)

In [23]:
df_scrape["cleaned_birth_date_formatted"].isna().sum()

73

In [24]:
df_scrape[df_scrape["cleaned_birth_date_formatted"].isna()][["birth_date", "cleaned_birth_date", "hhb_birth_date", "cleaned_birth_date_formatted"]]

,birth_date,cleaned_birth_date,hhb_birth_date,cleaned_birth_date_formatted
126,NaN,NaN,NaN,NaN
310,NaN,NaN,NaN,NaN
405,NaN,NaN,NaN,NaN
416,NaN,NaN,NaN,NaN
449,NaN,NaN,NaN,NaN
727,NaN,NaN,NaN,NaN
1023,NaN,NaN,NaN,NaN
1098,NaN,NaN,NaN,NaN
1497,NaN,NaN,NaN,NaN
1586,NaN,NaN,NaN,NaN
1631,NaN,NaN,NaN,NaN
1665,NaN,NaN,NaN,NaN
1670,NaN,NaN,NaN,NaN
1691,NaN,NaN,NaN,NaN
1848,NaN,NaN,NaN,NaN
2031,NaN,NaN,NaN,NaN
3177,NaN,NaN,NaN,NaN
3222,NaN,NaN,NaN,NaN
3303,NaN,NaN,NaN,NaN
5646,NaN,NaN,NaN,NaN
6147,NaN,NaN,NaN,NaN
6450,NaN,NaN,NaN,NaN
6888,NaN,NaN,NaN,NaN
6889,NaN,NaN,NaN,NaN
6893,NaN,NaN,NaN,NaN
7551,NaN,NaN,NaN,NaN
7769,19.4. (Geburtsjahr unbekannt),NaN,NaN,NaN
7774,NaN,NaN,NaN,NaN
7883,NaN,NaN,NaN,NaN
8197,NaN,NaN,NaN,NaN
8739,NaN,NaN,NaN,NaN
9049,NaN,NaN,NaN,NaN
10433,NaN,NaN,NaN,NaN
12064,NaN,NaN,NaN,NaN
12145,NaN,NaN,NaN,NaN
12477,NaN,NaN,NaN,NaN
12702,NaN,NaN,NaN,NaN
12808,NaN,NaN,NaN,NaN
14474,NaN,NaN,NaN,NaN
14988,NaN,NaN,NaN,NaN
15367,NaN,NaN,NaN,NaN
15440,NaN,NaN,NaN,NaN
16018,NaN,NaN,NaN,NaN
16189,NaN,NaN,NaN,NaN
16731,NaN,NaN,NaN,NaN
16787,NaN,NaN,NaN,NaN
16943,NaN,NaN,NaN,NaN
17171,NaN,NaN,NaN,NaN
17231,NaN,NaN,NaN,NaN
17294,NaN,NaN,NaN,NaN
17790,NaN,NaN,NaN,NaN
18029,NaN,NaN,NaN,NaN
18254,NaN,NaN,NaN,NaN
18531,NaN,NaN,NaN,NaN
19039,NaN,NaN,NaN,NaN
20220,NaN,NaN,NaN,NaN
20405,NaN,NaN,NaN,NaN
20854,NaN,NaN,NaN,NaN
22091,NaN,NaN,NaN,NaN
22334,NaN,NaN,NaN,NaN
22780,NaN,NaN,NaN,NaN
22794,NaN,NaN,NaN,NaN
22836,NaN,NaN,NaN,NaN
22837,NaN,NaN,NaN,NaN
22844,NaN,NaN,NaN,NaN
22845,NaN,NaN,NaN,NaN
22995,NaN,NaN,NaN,NaN
23054,NaN,NaN,NaN,NaN
23291,NaN,NaN,NaN,NaN
23527,NaN,NaN,NaN,NaN
23724,NaN,NaN,NaN,NaN
24077,NaN,NaN,NaN,NaN
24377,NaN,NaN,NaN,NaN

## Death Date

In [25]:
df_scrape["cleaned_death_date"] = df_scrape.death_date.str.extract(r"((\d{1,2}\.\d{1,2}\.\d{3,4})|(\d{3,4}))")[0]
# 8.8.1599 -> 1599-08-08
df_scrape["cleaned_death_date_formatted"] = df_scrape[df_scrape["cleaned_death_date"].str.fullmatch(r"(\d{1}\.\d{1}\.\d{4})", na=False)]["cleaned_death_date"].str.replace(r"(\d{1})\.(\d{1})\.(\d{4})", r"\3-0\2-0\1", regex=True)
# 8.8.900 -> 0900-08-08
df_scrape["cleaned_death_date_formatted"].fillna(df_scrape[df_scrape["cleaned_death_date"].str.fullmatch(r"(\d{1}\.\d{1}\.\d{3})", na=False)]["cleaned_death_date"].str.replace(r"(\d{1})\.(\d{1})\.(\d{3})", r"0\3-0\2-0\1", regex=True), inplace=True)
# 14.5.1900 -> 1900-05-14
df_scrape["cleaned_death_date_formatted"].fillna(df_scrape[df_scrape["cleaned_death_date"].str.fullmatch(r"(\d{2}\.\d{1}\.\d{4})", na=False)]["cleaned_death_date"].str.replace(r"(\d{2})\.(\d{1})\.(\d{4})", r"\3-0\2-\1", regex=True), inplace=True)
# 14.5.900 -> 0900-05-14
df_scrape["cleaned_death_date_formatted"].fillna(df_scrape[df_scrape["cleaned_death_date"].str.fullmatch(r"(\d{2}\.\d{1}\.\d{3})", na=False)]["cleaned_death_date"].str.replace(r"(\d{2})\.(\d{1})\.(\d{3})", r"0\3-0\2-\1", regex=True), inplace=True)
# 4.05.1900 -> 1900-05-04
df_scrape["cleaned_death_date_formatted"].fillna(df_scrape[df_scrape["cleaned_death_date"].str.fullmatch(r"(\d{1}\.\d{2}\.\d{4})", na=False)]["cleaned_death_date"].str.replace(r"(\d{1})\.(\d{2})\.(\d{4})", r"\3-\2-0\1", regex=True), inplace=True)
# 4.05.500 -> 0500-05-04
df_scrape["cleaned_death_date_formatted"].fillna(df_scrape[df_scrape["cleaned_death_date"].str.fullmatch(r"(\d{1}\.\d{2}\.\d{3})", na=False)]["cleaned_death_date"].str.replace(r"(\d{1})\.(\d{2})\.(\d{3})", r"0\3-\2-0\1", regex=True), inplace=True)
# 18.08.1500 -> 1500-08-18
df_scrape["cleaned_death_date_formatted"].fillna(df_scrape[df_scrape["cleaned_death_date"].str.fullmatch(r"(\d{2}\.\d{2}\.\d{4})", na=False)]["cleaned_death_date"].str.replace(r"(\d{2})\.(\d{2})\.(\d{4})", r"\3-\2-\1", regex=True), inplace=True)
# 18.08.900 -> 0900-08-18
df_scrape["cleaned_death_date_formatted"].fillna(df_scrape[df_scrape["cleaned_death_date"].str.fullmatch(r"(\d{2}\.\d{2}\.\d{3})", na=False)]["cleaned_death_date"].str.replace(r"(\d{2})\.(\d{2})\.(\d{3})", r"0\3-\2-\1", regex=True), inplace=True)
# 900 to 0900-01-01
df_scrape["cleaned_death_date_formatted"].fillna(df_scrape[df_scrape["cleaned_death_date"].str.fullmatch(r"(\d{3})", na=False)]["cleaned_death_date"].str.replace(r"(\d{3})", r"0\1-01-01", regex=True), inplace=True)
# 1500 to 1500-01-01
df_scrape["cleaned_death_date_formatted"].fillna(df_scrape[df_scrape["cleaned_death_date"].str.fullmatch(r"(\d{4})", na=False)]["cleaned_death_date"].str.replace(r"(\d{4})", r"\1-01-01", regex=True), inplace=True)

# fill missing dates with hhd_death_date
df_scrape.fillna({"cleaned_death_date_formatted": df_scrape.hhb_death_date}, inplace=True)

In [26]:
df_scrape["cleaned_death_date_formatted"].isna().sum()

472

In [28]:
pd.options.display.max_rows = 500
df_scrape[df_scrape["cleaned_death_date_formatted"].isna()][["death_date", "cleaned_death_date", "hhb_death_date", "cleaned_death_date_formatted"]]

,death_date,cleaned_death_date,hhb_death_date,cleaned_death_date_formatted
122,NaN,NaN,NaN,NaN
123,NaN,NaN,NaN,NaN
130,NaN,NaN,NaN,NaN
173,NaN,NaN,NaN,NaN
336,NaN,NaN,NaN,NaN
440,NaN,NaN,NaN,NaN
511,NaN,NaN,NaN,NaN
577,NaN,NaN,NaN,NaN
633,NaN,NaN,NaN,NaN
685,NaN,NaN,NaN,NaN
700,NaN,NaN,NaN,NaN
795,NaN,NaN,NaN,NaN
797,NaN,NaN,NaN,NaN
810,NaN,NaN,NaN,NaN
811,NaN,NaN,NaN,NaN
835,NaN,NaN,NaN,NaN
838,NaN,NaN,NaN,NaN
846,NaN,NaN,NaN,NaN
1150,NaN,NaN,NaN,NaN
1218,NaN,NaN,NaN,NaN
1219,NaN,NaN,NaN,NaN
1296,NaN,NaN,NaN,NaN
1512,NaN,NaN,NaN,NaN
1532,NaN,NaN,NaN,NaN
1554,19.1,NaN,NaN,NaN
1682,NaN,NaN,NaN,NaN
1819,NaN,NaN,NaN,NaN
1842,NaN,NaN,NaN,NaN
1848,NaN,NaN,NaN,NaN
1854,NaN,NaN,NaN,NaN
1866,NaN,NaN,NaN,NaN
1886,NaN,NaN,NaN,NaN
1888,NaN,NaN,NaN,NaN
1926,NaN,NaN,NaN,NaN
1995,NaN,NaN,NaN,NaN
2031,NaN,NaN,NaN,NaN
2085,NaN,NaN,NaN,NaN
2158,NaN,NaN,NaN,NaN
2233,NaN,NaN,NaN,NaN
2415,NaN,NaN,NaN,NaN
2488,NaN,NaN,NaN,NaN
2490,NaN,NaN,NaN,NaN
2491,NaN,NaN,NaN,NaN
2530,NaN,NaN,NaN,NaN
2577,NaN,NaN,NaN,NaN
2598,NaN,NaN,NaN,NaN
2600,NaN,NaN,NaN,NaN
2663,NaN,NaN,NaN,NaN
2723,NaN,NaN,NaN,NaN
2939,NaN,NaN,NaN,NaN
3021,NaN,NaN,NaN,NaN
3034,NaN,NaN,NaN,NaN
3091,NaN,NaN,NaN,NaN
3175,NaN,NaN,NaN,NaN
3192,NaN,NaN,NaN,NaN
3308,NaN,NaN,NaN,NaN
3479,NaN,NaN,NaN,NaN
3485,NaN,NaN,NaN,NaN
3529,NaN,NaN,NaN,NaN
3591,NaN,NaN,NaN,NaN
3625,NaN,NaN,NaN,NaN
3630,NaN,NaN,NaN,NaN
3728,NaN,NaN,NaN,NaN
3770,NaN,NaN,NaN,NaN
3838,NaN,NaN,NaN,NaN
3851,NaN,NaN,NaN,NaN
3947,NaN,NaN,NaN,NaN
3981,NaN,NaN,NaN,NaN
4109,NaN,NaN,NaN,NaN
4141,NaN,NaN,NaN,NaN
4226,NaN,NaN,NaN,NaN
4251,NaN,NaN,NaN,NaN
4275,NaN,NaN,NaN,NaN
4286,NaN,NaN,NaN,NaN
4337,NaN,NaN,NaN,NaN
4355,NaN,NaN,NaN,NaN
4405,NaN,NaN,NaN,NaN
4460,NaN,NaN,NaN,NaN
4461,NaN,NaN,NaN,NaN
4515,NaN,NaN,NaN,NaN
4597,NaN,NaN,NaN,NaN
4608,NaN,NaN,NaN,NaN
4616,NaN,NaN,NaN,NaN
4619,NaN,NaN,NaN,NaN
4631,NaN,NaN,NaN,NaN
4683,NaN,NaN,NaN,NaN
4695,NaN,NaN,NaN,NaN
4724,NaN,NaN,NaN,NaN
4768,NaN,NaN,NaN,NaN
4797,NaN,NaN,NaN,NaN
4871,NaN,NaN,NaN,NaN
4894,NaN,NaN,NaN,NaN
4967,NaN,NaN,NaN,NaN
4984,NaN,NaN,NaN,NaN
5005,NaN,NaN,NaN,NaN
5057,NaN,NaN,NaN,NaN
5161,NaN,NaN,NaN,NaN
5236,NaN,NaN,NaN,NaN
5238,NaN,NaN,NaN,NaN
5264,NaN,NaN,NaN,NaN
5311,NaN,NaN,NaN,NaN
5375,NaN,NaN,NaN,NaN
5380,NaN,NaN,NaN,NaN
5561,NaN,NaN,NaN,NaN
5565,NaN,NaN,NaN,NaN
5636,NaN,NaN,NaN,NaN
5750,NaN,NaN,NaN,NaN
5767,NaN,NaN,NaN,NaN
5870,NaN,NaN,NaN,NaN
5888,NaN,NaN,NaN,NaN
5893,NaN,NaN,NaN,NaN
5904,NaN,NaN,NaN,NaN
5919,NaN,NaN,NaN,NaN
5966,NaN,NaN,NaN,NaN
6019,2.5.,NaN,NaN,NaN
6040,NaN,NaN,NaN,NaN
6063,NaN,NaN,NaN,NaN
6114,NaN,NaN,NaN,NaN
6115,NaN,NaN,NaN,NaN
6122,NaN,NaN,NaN,NaN
6140,NaN,NaN,NaN,NaN
6158,NaN,NaN,NaN,NaN
6430,NaN,NaN,NaN,NaN
6442,NaN,NaN,NaN,NaN
6450,NaN,NaN,NaN,NaN
6625,NaN,NaN,NaN,NaN
6647,erstes Drittel 13. Jh.,NaN,NaN,NaN
6674,NaN,NaN,NaN,NaN
6678,NaN,NaN,NaN,NaN
6679,NaN,NaN,NaN,NaN
6842,NaN,NaN,NaN,NaN
6913,NaN,NaN,NaN,NaN
7067,NaN,NaN,NaN,NaN
7147,NaN,NaN,NaN,NaN
7189,NaN,NaN,NaN,NaN
7308,NaN,NaN,NaN,NaN
7343,NaN,NaN,NaN,NaN
7393,NaN,NaN,NaN,NaN
7426,NaN,NaN,NaN,NaN
7444,NaN,NaN,NaN,NaN
7552,NaN,NaN,NaN,NaN
7666,NaN,NaN,NaN,NaN
7668,NaN,NaN,NaN,NaN
7738,NaN,NaN,NaN,NaN
7774,NaN,NaN,NaN,NaN
7787,NaN,NaN,NaN,NaN
7807,NaN,NaN,NaN,NaN
7838,NaN,NaN,NaN,NaN
7922,NaN,NaN,NaN,NaN
7962,NaN,NaN,NaN,NaN
7982,NaN,NaN,NaN,NaN
7983,NaN,NaN,NaN,NaN
7994,NaN,NaN,NaN,NaN
8102,NaN,NaN,NaN,NaN
8106,NaN,NaN,NaN,NaN
8145,NaN,NaN,NaN,NaN
8271,NaN,NaN,NaN,NaN
8314,NaN,NaN,NaN,NaN
8494,NaN,NaN,NaN,NaN
8539,NaN,NaN,NaN,NaN
8659,NaN,NaN,NaN,NaN
8678,NaN,NaN,NaN,NaN
8759,NaN,NaN,NaN,NaN
8791,NaN,NaN,NaN,NaN
8794,NaN,NaN,NaN,NaN
8850,NaN,NaN,NaN,NaN
8914,NaN,NaN,NaN,NaN
8975,NaN,NaN,NaN,NaN
8981,NaN,NaN,NaN,NaN
9135,NaN,NaN,NaN,NaN
9187,NaN,NaN,NaN,NaN
9230,NaN,NaN,NaN,NaN
9232,NaN,NaN,NaN,NaN
9308,NaN,NaN,NaN,NaN
9487,NaN,NaN,NaN,NaN
9534,NaN,NaN,NaN,NaN
9544,NaN,NaN,NaN,NaN
9644,NaN,NaN,NaN,NaN
9815,NaN,NaN,NaN,NaN
9827,NaN,NaN,NaN,NaN
9930,NaN,NaN,NaN,NaN
10018,NaN,NaN,NaN,NaN
10190,NaN,NaN,NaN,NaN
10211,NaN,NaN,NaN,NaN
10216,NaN,NaN,NaN,NaN
10393,NaN,NaN,NaN,NaN
10415,NaN,NaN,NaN,NaN
10418,NaN,NaN,NaN,NaN
10433,NaN,NaN,NaN,NaN
10459,NaN,NaN,NaN,NaN
10477,NaN,NaN,NaN,NaN
10660,NaN,NaN,NaN,NaN
10680,NaN,NaN,NaN,NaN
10702,NaN,NaN,NaN,NaN
10817,NaN,NaN,NaN,NaN
10841,NaN,NaN,NaN,NaN
10843,NaN,NaN,NaN,NaN
10844,NaN,NaN,NaN,NaN
10848,NaN,NaN,NaN,NaN
10874,NaN,NaN,NaN,NaN
10940,NaN,NaN,NaN,NaN
10989,NaN,NaN,NaN,NaN
11137,gegen Ende des 15. Jahrhunderts.,NaN,NaN,NaN
11183,NaN,NaN,NaN,NaN
11192,NaN,NaN,NaN,NaN
11429,NaN,NaN,NaN,NaN
11502,NaN,NaN,NaN,NaN
11540,NaN,NaN,NaN,NaN
11672,NaN,NaN,NaN,NaN
11707,NaN,NaN,NaN,NaN
11827,NaN,NaN,NaN,NaN
11862,NaN,NaN,NaN,NaN
11880,NaN,NaN,NaN,NaN
11966,NaN,NaN,NaN,NaN
11996,NaN,NaN,NaN,NaN
12014,NaN,NaN,NaN,NaN
12093,NaN,NaN,NaN,NaN
12185,NaN,NaN,NaN,NaN
12207,NaN,NaN,NaN,NaN
12214,NaN,NaN,NaN,NaN
12232,NaN,NaN,NaN,NaN
12334,NaN,NaN,NaN,NaN
12341,NaN,NaN,NaN,NaN
12525,NaN,NaN,NaN,NaN
12622,NaN,NaN,NaN,NaN
12686,NaN,NaN,NaN,NaN
12757,NaN,NaN,NaN,NaN
12777,NaN,NaN,NaN,NaN
12793,NaN,NaN,NaN,NaN
12797,NaN,NaN,NaN,NaN
12800,NaN,NaN,NaN,NaN
12808,NaN,NaN,NaN,NaN
12820,NaN,NaN,NaN,NaN
12855,NaN,NaN,NaN,NaN
12944,NaN,NaN,NaN,NaN
12963,NaN,NaN,NaN,NaN
12989,NaN,NaN,NaN,NaN
13034,NaN,NaN,NaN,NaN
13055,NaN,NaN,NaN,NaN
13129,NaN,NaN,NaN,NaN
13211,NaN,NaN,NaN,NaN
13223,NaN,NaN,NaN,NaN
13231,NaN,NaN,NaN,NaN
13250,NaN,NaN,NaN,NaN
13261,NaN,NaN,NaN,NaN
13305,NaN,NaN,NaN,NaN
13422,NaN,NaN,NaN,NaN
13430,NaN,NaN,NaN,NaN
13498,NaN,NaN,NaN,NaN
13499,NaN,NaN,NaN,NaN
13579,NaN,NaN,NaN,NaN
13599,NaN,NaN,NaN,NaN
13639,NaN,NaN,NaN,NaN
13656,NaN,NaN,NaN,NaN
13703,NaN,NaN,NaN,NaN
13743,NaN,NaN,NaN,NaN
13753,NaN,NaN,NaN,NaN
13809,NaN,NaN,NaN,NaN
13822,NaN,NaN,NaN,NaN
13828,NaN,NaN,NaN,NaN
13845,NaN,NaN,NaN,NaN
13850,NaN,NaN,NaN,NaN
13857,NaN,NaN,NaN,NaN
13866,NaN,NaN,NaN,NaN
13883,NaN,NaN,NaN,NaN
13936,NaN,NaN,NaN,NaN
13978,NaN,NaN,NaN,NaN
13981,NaN,NaN,NaN,NaN
14038,NaN,NaN,NaN,NaN
14070,NaN,NaN,NaN,NaN
14142,NaN,NaN,NaN,NaN
14216,NaN,NaN,NaN,NaN
14375,NaN,NaN,NaN,NaN
14402,NaN,NaN,NaN,NaN
14429,NaN,NaN,NaN,NaN
14461,NaN,NaN,NaN,NaN
14474,NaN,NaN,NaN,NaN
14552,NaN,NaN,NaN,NaN
14604,NaN,NaN,NaN,NaN
14784,NaN,NaN,NaN,NaN
14806,NaN,NaN,NaN,NaN
14848,NaN,NaN,NaN,NaN
14942,NaN,NaN,NaN,NaN
14959,NaN,NaN,NaN,NaN
14992,NaN,NaN,NaN,NaN
15023,NaN,NaN,NaN,NaN
15081,NaN,NaN,NaN,NaN
15201,NaN,NaN,NaN,NaN
15285,NaN,NaN,NaN,NaN
15326,NaN,NaN,NaN,NaN
15367,NaN,NaN,NaN,NaN
15420,NaN,NaN,NaN,NaN
15440,NaN,NaN,NaN,NaN
15447,NaN,NaN,NaN,NaN
15464,NaN,NaN,NaN,NaN
15540,NaN,NaN,NaN,NaN
15541,NaN,NaN,NaN,NaN
15597,NaN,NaN,NaN,NaN
15608,NaN,NaN,NaN,NaN
15639,NaN,NaN,NaN,NaN
15701,NaN,NaN,NaN,NaN
15753,NaN,NaN,NaN,NaN
15814,NaN,NaN,NaN,NaN
15847,NaN,NaN,NaN,NaN
15913,NaN,NaN,NaN,NaN
15929,NaN,NaN,NaN,NaN
15981,NaN,NaN,NaN,NaN
16050,NaN,NaN,NaN,NaN
16115,NaN,NaN,NaN,NaN
16140,NaN,NaN,NaN,NaN
16143,NaN,NaN,NaN,NaN
16190,NaN,NaN,NaN,NaN
16215,NaN,NaN,NaN,NaN
16293,NaN,NaN,NaN,NaN
16378,NaN,NaN,NaN,NaN
16428,NaN,NaN,NaN,NaN
16451,NaN,NaN,NaN,NaN
16731,NaN,NaN,NaN,NaN
16762,NaN,NaN,NaN,NaN
16812,Anfang 8. Jahrhundert,NaN,NaN,NaN
16944,NaN,NaN,NaN,NaN
17064,NaN,NaN,NaN,NaN
17090,NaN,NaN,NaN,NaN
17107,NaN,NaN,NaN,NaN
17302,NaN,NaN,NaN,NaN
17351,NaN,NaN,NaN,NaN
17381,NaN,NaN,NaN,NaN
17529,NaN,NaN,NaN,NaN
17704,NaN,NaN,NaN,NaN
17726,NaN,NaN,NaN,NaN
17733,NaN,NaN,NaN,NaN
17745,NaN,NaN,NaN,NaN
17833,NaN,NaN,NaN,NaN
17872,NaN,NaN,NaN,NaN
17999,NaN,NaN,NaN,NaN
18146,NaN,NaN,NaN,NaN
18169,NaN,NaN,NaN,NaN
18291,NaN,NaN,NaN,NaN
18330,NaN,NaN,NaN,NaN
18363,NaN,NaN,NaN,NaN
18462,NaN,NaN,NaN,NaN
18474,NaN,NaN,NaN,NaN
18725,NaN,NaN,NaN,NaN
18919,NaN,NaN,NaN,NaN
18930,NaN,NaN,NaN,NaN
18932,NaN,NaN,NaN,NaN
18975,NaN,NaN,NaN,NaN
19003,NaN,NaN,NaN,NaN
19027,NaN,NaN,NaN,NaN
19043,NaN,NaN,NaN,NaN
19084,NaN,NaN,NaN,NaN
19119,NaN,NaN,NaN,NaN
19226,NaN,NaN,NaN,NaN
19227,NaN,NaN,NaN,NaN
19256,NaN,NaN,NaN,NaN
19472,NaN,NaN,NaN,NaN
19506,NaN,NaN,NaN,NaN
19608,NaN,NaN,NaN,NaN
19631,NaN,NaN,NaN,NaN
19646,NaN,NaN,NaN,NaN
19717,NaN,NaN,NaN,NaN
19718,NaN,NaN,NaN,NaN
19723,NaN,NaN,NaN,NaN
19751,NaN,NaN,NaN,NaN
19790,NaN,NaN,NaN,NaN
19860,NaN,NaN,NaN,NaN
19945,NaN,NaN,NaN,NaN
20012,NaN,NaN,NaN,NaN
20089,NaN,NaN,NaN,NaN
20108,NaN,NaN,NaN,NaN
20251,NaN,NaN,NaN,NaN
20290,NaN,NaN,NaN,NaN
20303,NaN,NaN,NaN,NaN
20305,NaN,NaN,NaN,NaN
20315,NaN,NaN,NaN,NaN
20324,NaN,NaN,NaN,NaN
20369,NaN,NaN,NaN,NaN
20435,NaN,NaN,NaN,NaN
20450,NaN,NaN,NaN,NaN
20464,NaN,NaN,NaN,NaN
20497,NaN,NaN,NaN,NaN
20540,NaN,NaN,NaN,NaN
20652,NaN,NaN,NaN,NaN
20653,NaN,NaN,NaN,NaN
20683,NaN,NaN,NaN,NaN
20776,NaN,NaN,NaN,NaN
20799,NaN,NaN,NaN,NaN
20814,NaN,NaN,NaN,NaN
20815,NaN,NaN,NaN,NaN
20890,NaN,NaN,NaN,NaN
20941,NaN,NaN,NaN,NaN
20955,NaN,NaN,NaN,NaN
20959,NaN,NaN,NaN,NaN
20975,NaN,NaN,NaN,NaN
21070,NaN,NaN,NaN,NaN
21093,NaN,NaN,NaN,NaN
21173,NaN,NaN,NaN,NaN
21278,NaN,NaN,NaN,NaN
21293,NaN,NaN,NaN,NaN
21304,NaN,NaN,NaN,NaN
21490,NaN,NaN,NaN,NaN
21876,NaN,NaN,NaN,NaN
21932,NaN,NaN,NaN,NaN
21964,NaN,NaN,NaN,NaN
21968,NaN,NaN,NaN,NaN
22046,NaN,NaN,NaN,NaN
22055,NaN,NaN,NaN,NaN
22117,NaN,NaN,NaN,NaN
22213,NaN,NaN,NaN,NaN
22255,NaN,NaN,NaN,NaN
22265,NaN,NaN,NaN,NaN
22273,NaN,NaN,NaN,NaN
22286,NaN,NaN,NaN,NaN
22289,NaN,NaN,NaN,NaN
22334,NaN,NaN,NaN,NaN
22596,NaN,NaN,NaN,NaN
22653,NaN,NaN,NaN,NaN
22662,NaN,NaN,NaN,NaN
22742,NaN,NaN,NaN,NaN
22786,NaN,NaN,NaN,NaN
22793,NaN,NaN,NaN,NaN
22795,NaN,NaN,NaN,NaN
22800,NaN,NaN,NaN,NaN
22802,NaN,NaN,NaN,NaN
22836,NaN,NaN,NaN,NaN
22866,NaN,NaN,NaN,NaN
22990,NaN,NaN,NaN,NaN
23092,NaN,NaN,NaN,NaN
23134,NaN,NaN,NaN,NaN
23142,NaN,NaN,NaN,NaN
23259,NaN,NaN,NaN,NaN
23327,30.10,NaN,NaN,NaN
23344,NaN,NaN,NaN,NaN
23349,NaN,NaN,NaN,NaN
23364,NaN,NaN,NaN,NaN
23463,NaN,NaN,NaN,NaN
23510,NaN,NaN,NaN,NaN
23518,NaN,NaN,NaN,NaN
23522,NaN,NaN,NaN,NaN
23546,NaN,NaN,NaN,NaN
23729,NaN,NaN,NaN,NaN
23797,NaN,NaN,NaN,NaN
23887,NaN,NaN,NaN,NaN
23921,NaN,NaN,NaN,NaN
23991,NaN,NaN,NaN,NaN
24005,NaN,NaN,NaN,NaN
24069,NaN,NaN,NaN,NaN
24082,NaN,NaN,NaN,NaN
24130,NaN,NaN,NaN,NaN
24134,NaN,NaN,NaN,NaN
24226,NaN,NaN,NaN,NaN
24271,NaN,NaN,NaN,NaN
24300,NaN,NaN,NaN,NaN
24310,NaN,NaN,NaN,NaN
24356,NaN,NaN,NaN,NaN
24485,NaN,NaN,NaN,NaN
24498,NaN,NaN,NaN,NaN
24606,NaN,NaN,NaN,NaN
24660,NaN,NaN,NaN,NaN
24661,NaN,NaN,NaN,NaN
24666,NaN,NaN,NaN,NaN
24706,NaN,NaN,NaN,NaN
24869,NaN,NaN,NaN,NaN
24879,NaN,NaN,NaN,NaN
24899,NaN,NaN,NaN,NaN
24952,NaN,NaN,NaN,NaN
24956,NaN,NaN,NaN,NaN
24975,NaN,NaN,NaN,NaN
25027,NaN,NaN,NaN,NaN
25100,NaN,NaN,NaN,NaN
25198,NaN,NaN,NaN,NaN
25217,NaN,NaN,NaN,NaN

In [31]:
df_scrape.drop("cleaned_birth_date",axis=1, inplace=True)
df_scrape.drop("cleaned_death_date",axis=1, inplace=True)

In [32]:
df_scrape.to_csv("hls_dump/22_10_22_hls_people_hist_hub_cleaned.csv", sep=";", index=False)

,HLS_ID,HLS_URL,first_name,last_name,birth_date,death_date,text,published,author,translator,...,hhb_forename,hhb_surname,hhb_sex,hhb_birth_date,hhb_death_date,hhb_relation_id,hhb_relation_name,hhb_relation_type,cleaned_birth_date_formatted,cleaned_death_date_formatted
0,25265,http://hls-dhs-dss.ch/de/articles/025265/2001-...,Johann Ludwig,A Musis,8.8.1599,10.6.1662,"8.8.1599 Pfullendorf (Baden, D), 10.6.1662 Sol...",10.05.2001,Urban Fink,NaN,...,Johann Ludwig,A Musis,male,1599-08-08,1662-06-10,NaN,NaN,NaN,1599-08-08,1662-06-10
1,27932,http://hls-dhs-dss.ch/de/articles/027932/2002-...,Carlo Emanuele,A Prato,7.4.1895,17.9.1968,"7.4.1895 Trient, 17.9.1968 Genf, ursprünglich ...",21.08.2002,Mauro Cerutti,Christoph Neuenschwander,...,Carlo Emanuele,A Prato,male,1895-04-07,1968-09-17,NaN,NaN,NaN,1895-04-07,1968-09-17
2,4928,http://hls-dhs-dss.ch/de/articles/004928/2002-...,Albert von der,Aa,19.1.1894,10.7.1978,"19.1.1894 Vevey, 10.7.1978 Lausanne, reformier...",11.06.2002,Gilbert Marion,Peter Opitz,...,Albert,von der Aa,male,1894-01-19,1978-07-10,NaN,NaN,NaN,1894-01-19,1978-07-10
3,11462,http://hls-dhs-dss.ch/de/articles/011462/2001-...,Johannes,Aal,um 1500,28.5.1551,"um 1500 Bremgarten (AG), 28.5.1551 Solothurn, ...",24.01.2001,Rolf Max Kully,NaN,...,Johannes,Aal,male,1500-01-01,1551-05-28,NaN,NaN,NaN,1500-01-01,1551-05-28
4,8115,http://hls-dhs-dss.ch/de/articles/008115/2001-...,Alvar,Aalto,3.2.1898,11.5.1976,"3.2.1898 Kuortane (Finnland), 11.5.1976 Helsin...",15.05.2001,Simona Martinoli,Sabine Kraut,...,Alvar,Aalto,male,1898-02-03,1976-05-11,NaN,NaN,NaN,1898-02-03,1976-05-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25266,27791,http://hls-dhs-dss.ch/de/articles/027791/2013-...,Giovanni,Züst,24.1.1887,4.12.1976,"24.1.1887 Basel, 4.12.1976 Rancate (heute Geme...",24.04.2013,Mariangela Agliati Ruggia,Christa Mathys,...,Giovanni,Züst,male,1887-01-24,1976-12-04,NaN,NaN,NaN,1887-01-24,1976-12-04
25267,30267,http://hls-dhs-dss.ch/de/articles/030267/2013-...,Hansruedi,Züst,11.11.1921,22.11.2005,"11.11.1921 Rheineck, 22.11.2005 Zürich, reform...",28.01.2013,Adrian Scherrer,NaN,...,Hansruedi,Züst,male,1921-11-11,2005-11-22,NaN,NaN,NaN,1921-11-11,2005-11-22
25268,21194,http://hls-dhs-dss.ch/de/articles/021194/2008-...,Rudolf von,Ödisried,7.3.1304,1332,"Erstmals erwähnt 7.3.1304, 1332 oder kurz dana...",04.11.2008,Niklaus von Flüe,NaN,...,Rudolf,von Ödisried,male,1304-01-01,1332-01-01,NaN,NaN,NaN,1304-03-07,1332-01-01
25269,18772,http://hls-dhs-dss.ch/de/articles/018772/2009-...,Gallus,Öhem,um 1445,1522,"um 1445 Radolfzell, 1522 Freiburg i.Br. Illegi...",20.08.2009,Veronika Feller-Vest,NaN,...,Gallus,Öhem,male,1445-01-01,1522-01-01,NaN,NaN,NaN,1445-01-01,1522-01-01
25270,26337,http://hls-dhs-dss.ch/de/articles/026337/2001-...,Andreas von,Österreich,15.6.1558,12.11.1600,"15.6.1558 Burg Bresnitz (Böhmen), 12.11.1600 R...",21.11.2001,Herbert Frey,NaN,...,Andreas,von Österreich,male,1558-06-15,1600-11-12,NaN,NaN,NaN,1558-06-15,1600-11-12